services:
    ThijsFeryn\Bundle\EdgestashTwigBundle\TwigExtension:
        arguments:
            - '@request_stack'
        tags: ['twig.extension']
    ThijsFeryn\Bundle\EdgestashTwigBundle\EventSubscriber\EdgestashTwigSubscriber:
        tags: ['kernel.event_subscriber']